TRAIN:
    model: singlepath
    workers: 3
    
    arch: [0,1,2,2,1,1,2,1,3,3,0,3,0,3,0,0,2,2,2,1]
    evaluate: True
    bn_affine: True
    bn_eps: 0.00001 

    print_freq: 100
    model_dir: ckpts_1_5_x

    checkpoint_path: models/SPOSretrain240.pth
    val_root: /mnt/lustre/share/images/val
    val_source: /mnt/lustre/share/images/meta/val.txt

